export const CREATE_NEWSLETTER = 'CREATE_NEWSLETTER';
export const TOKEN_KEY = 'TOKEN_KEY';
export const CREATE_PATIENT = 'CREATE_PATIENT';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const CREATE_ABOUT = 'CREATE_ABOUT';
export const EDIT_PATIENT_ABOUT = 'EDIT_PATIENT_ABOUT';
export const FETCH_ABOUT = 'FETCH_ABOUT';
export const CREATE_CONTACTINFO = 'CREATE_CONTACTINFO';
export const FETCH_TAILLE_METRIX = 'FETCH_TAILLE_METRIX';
export const CREATE_TAILLE_METRIX = 'CREATE_TAILLE_METRIX';
export const EDIT_TAILLE_METRIX = 'EDIT_TAILLE_METRIX';
export const DELETE_TAILLE_METRIX = 'DELETE_TAILLE_METRIX';
export const CREATE_POIDS_METRIX = 'CREATE_POIDS_METRIX';
export const EDIT_POIDS_METRIX = 'EDIT_POIDS_METRIX';
export const DELETE_POIDS_METRIX = 'DELETE_POIDS_METRIX';


